### ISSUE TITLE
为什么换了appid就无法识别了呢？

### ISSUE THREAD

**Issue by wzpan** [ssky87/iflytek_sdk_python#2]
谢谢作者的 demo 。

我试着将 stt.py 中的 appid 换成了我的应用的 appid （应用已绑定了语音听写的功能），再次执行程序时，一直识别不出结果。[第 108 行的 x 变量](https://github.com/ssky87/iflytek_sdk_python/blob/master/stt.py#L108) 一直为 None ，跳不出 while 循环。

请问这是什么原因呢？

**Comment by wzpan** [comment]
知道原因了，换了 appid 后，so 包也要跟着换。

**Comment by ssky87** [comment]
嗯，科大讯飞sdk里面有写的，so跟appid绑定的
